config/routes.rb
Ovia::Application.routes.draw do  

  root :to => 'categories#index'

  resources :pages, :only => :show
    
  resources :categories do    
    resources :products    
  end
  
    
  resources :projects do
    resources :tickets
  end
  
  resources :tickets  do
    resources :comments
  end
  
  resources :files, :images
  
  get "users/confirmation"

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  
  namespace :admin do    
    root :to => 'base#index'
    resources :pages, :categories, :colors, :sizes,:orders
        
    resources :users do
      resources :permissions
    end
        
    resources :product_options do          
      resources :product_option_variations
    end
    
    resources :products do          
      resources :color_sizes
    end    
    
    resources :states do
      member do
        get :make_default
      end
    end   
  end
  
  
  
  put '/admin/users/:user_id/permissions',
            :to => 'admin/permissions#update',
            :as => :update_user_permissions
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
    def initialize(user)
      user.permissions.each do |permission|
        can permission.action.to_sym, permission.thing_type.constantize do |thing|
          thing.nil? ||
          permission.thing_id.nil? ||
          permission.thing_id == thing.id
      end
    end
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_attached_file :asset, :path => (Rails.root + "files/:id").to_s,
                            :url => "/files/:id"
  belongs_to :ticket
end

app/models/category.rb
class Category < ActiveRecord::Base
    
  has_many :products, :dependent => :destroy
  
  validates :name,        :presence => true,
                          :length => { :maximum => 50 },
                          :uniqueness => true
                          
  validates :description, :presence => true,
                          :length => { :maximum => 160 }                
  
  default_scope :order => 'categories.created_at DESC'  
  
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/color.rb
class Color < ActiveRecord::Base 
  has_many :color_sizes
  has_many :products, :through => :color_sizes
  validates :name,        :presence => true
  
  def to_s
    name
  end
end

app/models/color_size.rb
class ColorSize < ActiveRecord::Base
  belongs_to :product
  belongs_to :size
  belongs_to :color  
  validates :size_id, :color_id, :product_id, :quantity, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  before_create :set_previous_state
  after_create :set_ticket_state
  
  belongs_to :ticket
  belongs_to :user
  belongs_to :state
  belongs_to :previous_state, :class_name => "State"
  
  delegate :project, :to => :ticket
  
  validates :text, :presence => true
  
  
  
  private
  
    def set_ticket_state
      self.ticket.state = self.state
      self.ticket.save!
    end
    
    def set_previous_state
      self.previous_state = ticket.state
    end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product 
  has_attached_file :image, :path => ":rails_root/images/:id",
                            :url => "/images/:id"
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
  validates :order_no,        :presence => true
  validates :total_amount,    :presence => true
  
  default_scope :order => 'orders.updated_at DESC'
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ActiveRecord::Base
  
  validates :name,        :presence => true
  validates :content,     :presence => true
  
  extend FriendlyId
  friendly_id :name, use: :slugged                       
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  #attr_accessible :name, :code, :price, :quantity, :description, :category_id  
  belongs_to :category
  belongs_to :user
  has_many :color_sizes
  has_many :sizes, :through => :color_sizes
  has_many :colors, :through => :color_sizes
  has_many :order_items
  has_many :images, :dependent => :destroy  
  accepts_nested_attributes_for :images  
  
  validates :name,        :presence => true    
  validates :code,        :presence => true,
                          :uniqueness => true,
                          :numericality => { :only_integer => true }                                                    
  validates :price,       :presence => true,
                          :numericality => true                          
  validates :description, :presence => true, 
                          :length => { :maximum => 140 }                          
  validates :category_id, :presence => true
    
  #default_scope :order => 'products.created_at DESC'
  scope :visible, where(:visible => true)
  scope :invisible, where(:visible => false)
  
  
  extend FriendlyId
  friendly_id :code, use: :slugged  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :tickets, :dependent => :delete_all
  
  validates :name, :presence => true, :uniqueness => true
  
  has_many :permissions, :as => :thing
  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => { :action => "view",
                                                :user_id => user.id })
  }
  
  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end                           
end

app/models/size.rb
class Size < ActiveRecord::Base    
  has_many :color_sizes
  has_many :products, :through => :color_sizes
  validates :name,        :presence => true
  
  def to_s
    name
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :state
  
  def to_s
    name
  end
  
  def default!
    current_default_state = State.find_by_default(true)    
    self.default = true
    self.save!    
    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :state
  has_many :assets
  accepts_nested_attributes_for :assets
  has_many :comments
  has_and_belongs_to_many :tags
  
  validates :title,         :presence => true
  
  validates :description,   :presence => true,
                            :length => { :minimum => 10 }
                            
  def tag!(tags)
    tags = tags.split(" ").map do |tag|
      Tag.find_or_create_by_name(tag)
    end
    self.tags << tags
  end
  
  def to_param
     "#{id}-#{title.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :permissions
  has_many :orders
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def to_s
  "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/views/admin/_footer.html.erb
<br class="clear" />
<hr />
<footer>    
    <ul class="nav pull-left">
        <li>Copyright 2012 Milan Mondal, All rights reserved</li>
		</ul>	
		 <ul class="nav nav-pills pull-right">
	        <li class="active"><%= link_to "Home", '' %> </li>            
	        <li><%= link_to "About Us", "" %></li>
	        <li><%= link_to "Contact", "" %></li>
	        <li><%= link_to "Sign in", '#' %></li>
			</ul>
</footer>
<br class="clear" />
<%= debug(params) if Rails.env.development? %>

app/views/admin/_header.html.erb
<header>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				
					<%= link_to "Ovia", admin_root_path, :class => "brand" %>
					
					<ul class="nav pull-left">
						<li class="divider-vertical"></li>												
						<li><%= link_to "Users", admin_users_path %></li>
						<li class="divider-vertical"></li>
						<li><%= link_to "Orders", admin_orders_path %></li>
						<li class="divider-vertical"></li>
						<li><%= link_to "Categories", admin_categories_path %></li>
						<li class="divider-vertical"></li>
						<li><%= link_to "Products", admin_products_path %></li>
						<li class="divider-vertical"></li>						
						<li><%= link_to "States", admin_states_path %></li>
						<li class="divider-vertical"></li>					
					</ul>
			
				
				<ul class="nav pull-right">
					<li class ="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="icon-cog icon-white"> </i> Settings
							    <span class="caret"></span> <!--drop down icon-->
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Product Options", admin_product_options_path %></li>
								<li><%= link_to "Pages", admin_pages_path %></li>
								<li><%= link_to "Sizes", admin_sizes_path %></li>
								<li><%= link_to "Colors", admin_colors_path %></li>
							</ul>
					</li>
					<li class="divider-vertical"></li>	
					<li><%= link_to "Go Front", root_path, :target => "_blank" %></li>
					<li class="divider-vertical"></li>	
					<li id="header_link"><%= link_to("Sign out", destroy_user_session_path, :method => :delete) %></li>
				</ul>
			</div>
		</div>
	</div>
</header>
​

app/views/admin/pages/_form.html.erb
<%= simple_form_for [:admin, @page] do |f| %>
	<%= f.error_messages %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :content %>
	<%= f.text_area :content %><br/>
	<%= f.submit :class => 'btn' %>
<% end %>

app/views/admin/pages/edit.html.erb
<h2>Edit Category</h2>
<hr />
<%= render "form" %>

app/views/admin/pages/index.html.erb
<h1>Pages list</h1> 
<p class="lead">
	Showing all "<strong><%= @pages.count %></strong>" Pages.
</p>
<%= link_to "New Page", new_admin_page_path,  :class => 'btn btn-primary' %>
<hr />
<table class="table table-striped">
		<thead>
			<tr>
				<th>Page Name</th>
				<th>Action</th>
				<th>Last Updated</th>
			</tr>
		</thead>
		
		<% @pages.each do |page| %>
		<tr>
			<td><b><%= link_to page.name, admin_page_path(page.id) %></b>
			</td>
			
			<td>
					<%= link_to "", admin_page_path(page.id) , :class => "icon-search" %>
					<%= link_to "", edit_admin_page_path(page.id), :class => "icon-pencil" %>
					<%= link_to "", admin_page_path(page.id), :class => "icon-remove", 
													:method => :delete,
													:confirm => "Are you sure you want to delete this page?"%>
			</td>
			<td><b><%= time_ago_in_words(page.updated_at) %> ago<b></td>
		</tr>
		<% end %>
</table>

app/views/admin/pages/new.html.erb
<h2>New Page</h2>
<hr />
<%= render "form" %>

app/views/admin/pages/show.html.erb
<h1><%= @page.name %></h1>
<hr />
<p class="lead">	
	 <%= raw @page.content %>
</p>

<%= link_to "Edit Page", edit_admin_page_path(@page), :class => 'btn btn-primary'  %>

<%= link_to "Delete Page", admin_page_path(@page),	
													:method => :delete,
													:confirm => "Are you sure you want to delete this page?", 
													:class => 'btn' %>