config/routes.rb
Ovia::Application.routes.draw do  

  root :to => 'categories#index'

  resources :pages, :only => :show
    
  resources :categories do    
    resources :products    
  end
  
    
  resources :projects do
    resources :tickets
  end
  
  resources :tickets  do
    resources :comments
  end
  
  resources :files, :images
  
  get "users/confirmation"

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  
  namespace :admin do    
    root :to => 'base#index'
    resources :pages, :categories, :colors, :sizes,:orders
        
    resources :users do
      resources :permissions
    end
        
    resources :product_options do          
      resources :product_option_variations
    end
    
    resources :products do          
      resources :color_sizes
    end    
    
    resources :states do
      member do
        get :make_default
      end
    end   
  end
  
  
  
  put '/admin/users/:user_id/permissions',
            :to => 'admin/permissions#update',
            :as => :update_user_permissions
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :tickets, :dependent => :delete_all
  
  validates :name, :presence => true, :uniqueness => true
  
  has_many :permissions, :as => :thing
  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => { :action => "view",
                                                :user_id => user.id })
  }
  
  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end                           
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :find_project, :only => [ :show, :edit, :update,  :destroy]
  
  def index
    @projects = Project.for(current_user).all
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :new
    end
  end
  
  def show    
  end
  
  def edit    
  end
  
  def update    
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :edit
    end
  end
  
  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end
  
  private  
    def find_project
      @project = Project.for(current_user).find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
      " for could not be found."
      redirect_to projects_path
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
    <%= f.error_messages %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br />
    <%= f.submit :class => 'btn btn-large btn-primary' %>
<% end %> 

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<hr />
<%= render "form" %>

app/views/projects/index.html.erb
<h2>Projects</h2> 
<ul id="projects">
		<hr />
    <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
    <hr />
    <% end %>
</ul>
<%= admins_only do %>
    <%= link_to "New Project", new_project_path, :class =>" btn btn-large" %>
<% end %>
<br />
​

app/views/projects/new.html.erb
<h2>New project</h2>
<hr />
<%= render "form" %>

app/views/projects/show.html.slim
h2 
	= @project.name 
hr
= admins_only do 
	= link_to "Edit Project", edit_project_path(@project), :class => "btn btn-large btn-primary" 
	= link_to "Delete Project", @project, :method => :delete, :confirm => "Are you sure you want to delete this project?", :class => "btn btn-large btn-danger"

= authorized?("create tickets".to_sym, @project) do 
	= link_to "New Ticket", new_project_ticket_path(@project), :class => "btn btn-large btn-success"

hr

ul id='tickets'
	- @project.tickets.each do |ticket|
			li
				##{ticket.id } - #{link_to ticket.title, [@project, ticket]}