config/routes.rb
Ovia::Application.routes.draw do  

  root :to => 'categories#index'

  resources :pages, :only => :show
    
  resources :categories do    
    resources :products    
  end
  
    
  resources :projects do
    resources :tickets
  end
  
  resources :tickets  do
    resources :comments
  end
  
  resources :files, :images
  
  get "users/confirmation"

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  
  namespace :admin do    
    root :to => 'base#index'
    resources :pages, :categories, :colors, :sizes,:orders
        
    resources :users do
      resources :permissions
    end
        
    resources :product_options do          
      resources :product_option_variations
    end
    
    resources :products do          
      resources :color_sizes
    end    
    
    resources :states do
      member do
        get :make_default
      end
    end   
  end
  
  
  
  put '/admin/users/:user_id/permissions',
            :to => 'admin/permissions#update',
            :as => :update_user_permissions
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  #attr_accessible :name, :code, :price, :quantity, :description, :category_id  
  belongs_to :category
  belongs_to :user
  has_many :color_sizes
  has_many :sizes, :through => :color_sizes
  has_many :colors, :through => :color_sizes
  has_many :order_items
  has_many :images, :dependent => :destroy  
  accepts_nested_attributes_for :images  
  
  validates :name,        :presence => true    
  validates :code,        :presence => true,
                          :uniqueness => true,
                          :numericality => { :only_integer => true }                                                    
  validates :price,       :presence => true,
                          :numericality => true                          
  validates :description, :presence => true, 
                          :length => { :maximum => 140 }                          
  validates :category_id, :presence => true
    
  #default_scope :order => 'products.created_at DESC'
  scope :visible, where(:visible => true)
  scope :invisible, where(:visible => false)
  
  
  extend FriendlyId
  friendly_id :code, use: :slugged  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_filter :find_category
  before_filter :new_product, :only => [:index, :new]
  before_filter :find_product, :only => [:show, :edit,  :update, :destroy]
  
  def index
    if params[:scope]
       @products = Product.invisible.page(params[:page])
    else 
      @products = Product.visible
    end         
  end
  
  def new
  end
 
  def create
    @product = Product.new(params[:product].merge!(:user => current_user))    
    if @product.save
      flash[:notice] = "Product has been created."
      redirect_to [:admin, @product]
    else
      flash[:alert] = "Product has not been created."
      render :new
    end
  end
  
  def show
    @color_sizes = @product.color_sizes.all    
  end
  
  def edit    
  end
  
  def update
    if @product.update_attributes(params[:product])
      flash[:notice] = "Product has been updated."
      redirect_to [:admin, @product]
    else
      flash[:alert] = "Product has not been updated."
      render :edit
    end
  end
  
  def destroy
    @product.destroy
    flash[:notice] = "Product has been deleted."
    redirect_to admin_products_path
  end
 
 private 
  def new_product
    @product = Product.new
    @product.images.build
  end
  
  def find_category
    @categories = Category.all
  end
  def find_product
    @product = Product.find(params[:id])
  end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show    
    @product = Product.visible.find(params[:id])                        
    @title =  "#{@product.category.name} #{@product.code}"
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<hr />
<%= simple_form_for [:admin, @product], :html => { :multipart => true } do |f| %>
	<%= f.error_messages %>
	<div class="span3">	
		<%= f.input :name %>
		<%= f.input :code %>
		<%= f.input :price, :placeholder => 'Enter Price in Pound.' %>
		<%= f.input :quantity %>
		<%= f.select :category_id, @categories.map { |s| [s.name, s.id] }, 
					 :selected => @product.category_id %>
	</div>
	<div class="span3">	
		<%= f.input :description %> <hr/>
		<%= f.input :visible, :label => false, :inline_label =>"Show on Website." %><hr/>
		<% number = 0 %>
		<%= render 	:partial => "images/form", :locals => { :number => number } %>
		<%= link_to "Add another image", 'javascript:', :class => "btn", :id => "add_another_image" %> 					
		<br/>		
	</div>
	<%= f.button :submit, :class => 'btn btn-primary' %>
<% end %>

app/views/admin/products/_products_list.html.erb
<hr />
<table class="table table-striped" summary="Products List" id="data-list">
	<thead>
		<tr>
			<th>Product Name</th>
			<th>Code</th>
			<th>Price</th>
			<th>Stock</th>
			<th>Visible?</th>
			<th>Category</th>
			<th>Action</th>
			<th>Last Updated</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><b><%= link_to product.name, admin_product_path(product) %></b></td>
			<td><b><span class="code"><%= product.code %></span></b></td>
			<td><%= number_to_currency(product.price, :unit => "£") %></td>
			<td><%= product.quantity %></td>
			<td><%= product.visible %></td>
			<td><%= product.category.name %></td>		
			<td><%= link_to icon(:show), admin_product_path(product) %>
					<%= link_to icon(:edit), edit_admin_product_path(product) %>
					<%= link_to icon(:delete), admin_product_path(product), :method => :delete,
							:confirm => "Are you sure you want to delete this product?"%></td>
			<td><b><%= time_ago_in_words(product.updated_at) %> ago by<b></td>		
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/products/edit.html.erb
<h2>Edit Products</h2>
<%= render "form" %>

app/views/admin/products/index.html.erb
<div class="row">
	<div class="span8">
		<h2> <%= link_to "Home", admin_root_path %> / Product list </h2>
		<span class="lead">
			Showing <strong><%= @products.count %></strong> of <%= Product.count %>
		</span>
	</div>
	<div class="span4 pull-right">
		<a href="#" class='btn btn-success btn-large' data-toggle="collapse" data-target="#new-product">
			New Product
		</a>
		<button class='btn btn-primary btn-large' data-toggle="collapse" data-target="#demo">
		  <i class="icon-chevron-down"> </i> Filter 
		</button>
		<%= link_to "Disable Product (#{@products.invisible.count})", "?scope=invisible", :class => "btn btn-large btn-primary disabled" %>		
  </div>
</div>

<!-- filter data collapsible -->
<div id="new-product" class="collapse">
  <%= render "form" %>
</div>

<div id="demo" class="collapse">
	<hr/>
	<div class="input-append date" id="dp3" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
	<input class="span2" size="16" type="text" value="12-02-2012" readonly="">
	<span class="add-on"><i class="icon-th"></i></span>
	</div>
</div>
<!-- filter data collapsible -->

<%= render 'products_list' %>

app/views/admin/products/new.html.erb
<h2>New Products</h2>
<%= render "form" %>

app/views/admin/products/show.html.erb
<% if @product.images.exists? %>
	<div class="images span2">
		<ul class="thumbnails" >
		<% @product.images.each do |image| %>
			<li class="span3" style="overflow:hidden">
				<%= link_to image_tag((image.image.url), :width => "150") , image.image.url %>							
			</li>
		<% end %>
		</ul>
	</div>
<% end %>
<div class= "span4">
	<h1><%= @product.name %></h1>
	<h2>Code: <%= @product.code %></h2>
	<% if @product.price? %>
		<h3>Price: <%= number_to_currency(@product.price, :unit => "£") %></h3>
	<% end %>
	<p class="lead"><%= @product.description %></p>	
	<p>From Category <b><%= @product.category.name %></b></p>	
	<p>
		<% if @product.visible? %>
				<b>This product is enabled.</b>
		<% else %>			
				<b>This product is disabled. Click edit to enable it.</b>
		<% end %>			
	</p>
</div>

<br class= "clear">
<hr />
<%= link_to "Edit Product" , edit_admin_product_path(@product), :class => 'btn btn-primary' %>

<%= link_to "Stock Details", admin_product_color_sizes_path(@product), :class => 'btn' %>

<%= link_to "Delete Product" , admin_product_path(@product), 
	:class => 'btn', :method => :delete,	:confirm => "Are you sure you want to delete this product?" %>
	