config/routes.rb
Ovia::Application.routes.draw do  

  root :to => 'categories#index'

  resources :pages, :only => :show
    
  resources :categories do    
    resources :products    
  end
  
    
  resources :projects do
    resources :tickets
  end
  
  resources :tickets  do
    resources :comments
  end
  
  resources :files, :images
  
  get "users/confirmation"

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  
  namespace :admin do    
    root :to => 'base#index'
    resources :pages, :categories, :colors, :sizes,:orders
        
    resources :users do
      resources :permissions
    end
        
    resources :product_options do          
      resources :product_option_variations
    end
    
    resources :products do          
      resources :color_sizes
    end    
    
    resources :states do
      member do
        get :make_default
      end
    end   
  end
  
  
  
  put '/admin/users/:user_id/permissions',
            :to => 'admin/permissions#update',
            :as => :update_user_permissions
  
end

app/models/category.rb
class Category < ActiveRecord::Base
    
  has_many :products, :dependent => :destroy
  
  validates :name,        :presence => true,
                          :length => { :maximum => 50 },
                          :uniqueness => true
                          
  validates :description, :presence => true,
                          :length => { :maximum => 160 }                
  
  default_scope :order => 'categories.created_at DESC'  
  
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  
   before_filter :find_category, :only => [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all    
  end

  def new
    @category = Category.new
  end

  def create    
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Category has been created."
      redirect_to admin_categories_path
    else
      flash[:alert] = "Category has not been created."
      render :new
    end
  end

  def show
    @products = @category.products.order(params[:by]).page(params[:page])    
  end

  def edit
  end

  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category has been updated."
      redirect_to admin_categories_path
    else
      flash[:alert] = "Category has not been updated."
      render :edit
    end
  end

  def destroy
     @category.destroy
     flash[:notice] = "Category has been deleted."
     redirect_to admin_categories_path
  end

  private  
    def find_category
      @category = Category.find(params[:id])
    end

end
  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController    
  
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @products = @category.products.visible
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="hero-unit">
	<h1>Welcome you! </h1>
	<p class="lead">
		To UK's Best Asian Fashion brand Rupali's webportal. Please enjoy your stay.
	</p>
</div>
<hr/>
<ul id='categories' class="thumbnails">
	<% @categories.each do |category| %>
		<li class="span2">									
			<%= link_to image_tag("default_thumb.jpg"), category %> <br class="clear" />				
			<%= link_to category.name, category_path(category) %>	
		</li>
	<% end %>
<ul>
<br class="clear"/>

	

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<b><%= @category.description %></b>
<hr />
<ul id="products" class="thumbnails">
	<% @products.each do |product| %>		
		<li class="span3">
				<div>	
						<% if product.images.exists? %>		
							<% product.images.each do |image| %>				
									<%= link_to image_tag((image.image.url)), [@category, product] %>			
							<% end %>			
						<% else %>		
								<%= link_to image_tag("default_thumb.jpg"), [@category, product] %>		
						<% end %>					
				</div>
			<br /> 
			<b>Design No <%=product.code %><br /> 
			<%= number_to_currency(product.price, :unit => "£") %></b>
			<p><%= truncate(product.description, :length => 35) %></p>
		</li>		
	<% end %>
<ul>
<br class="clear">